version: "3.8"
services:
  mongo:
    image: 'mongo'
    container_name: 'mongo'
    environment:
    - MONGO_INITDB_DATABASE=appdb
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
    - ./mongo-volume:/data/db
    ports:
    - '27017-27019:27017-27019'

  pulsar:
    image: 'apachepulsar/pulsar:2.6.2'
    ports:
    - '6650:6650'
    - '8080:8080'
    command: bin/pulsar standalone
